### ISSUE TITLE
Master side : auth

### ISSUE THREAD

**Issue by aungminzan** [aungminzan/attendance#9]
## Description
Master side authentication. Login and Logout page.

## Task List
- [x] Create auth master
- [x] Create master login controller
- [x] Create master login page
